/* Display all Records */
SELECT * 
FROM swiggy;

/* List all customers who have placed at least one order. */
SELECT id, SUM(Total_ratings) AS Total_orders
FROM swiggy
GROUP BY id
HAVING SUM(id);

/*  Display all customers who have never placed an order     */
SELECT id
FROM swiggy
WHERE Total_ratings is NULL;

/* Find the total revenue generated by each restaurant.  */
SELECT Restaurant,SUM(Price) AS Revenue
FROM swiggy
GROUP BY Restaurant;

/*  Find the top 5 restaurants with the highest average rating.  */
SELECT Restaurant, SUM(Avg_ratings) AS Average_Ratings
FROM swiggy
GROUP BY Restaurant
ORDER BY SUM(Avg_ratings) desc
LIMIT 5;

/*  Find the Delivery Time Analysis by Area  */
SELECT AREA,ROUND(AVG(delivery_time),2) AS Average_Delivery_time
FROM swiggy
GROUP BY area
ORDER BY average_Delivery_time;

/* Find the minimum, maximum, and average price of meals for restaurants in the Indiranagar area.  */
SELECT 
    MIN(Price) AS Min_Price,
    MAX(Price) AS Max_Price,
    AVG(Price) AS Avg_Price
FROM swiggy
WHERE Area = 'Indiranagar';

/*  Find the average meal price for each area.   */
SELECT Area, AVG(Price) AS Avg_Price
FROM swiggy
GROUP BY Area;

/* Display all customers who live in 'Delhi'. */
SELECT id 
FROM swiggy
WHERE city='Delhi';

/*  Find the average rating of all restaurants in 'Mumbai' */
SELECT ROUND(AVG(Avg_ratings),2) AS Average_Ratings
FROM swiggy
WHERE city='Mumbai';

/* List all customers who have placed at least one order.   */
SELECT id 
FROM swiggy
where Total_ratings>1;

/* Display the total number of orders placed by each customer.   */
SELECT id, SUM(Total_ratings) AS Total_orders
FROM swiggy
GROUP BY id;

/*  Find the total number of restaurants in each city.   */
SELECT City, COUNT(Restaurant) AS Total_Restaurants
FROM swiggy
GROUP BY City;

/* Find all restaurants that offer both North Indian and Chinese cuisine. */
SELECT Restaurant, Area, City
FROM swiggy
WHERE Food_type LIKE '%North Indian%' AND Food_type LIKE '%Chinese%';
